packages:
  - "apps/*"
  - "packages/components/common/*"
  - "packages/components/sections/*"
  - "packages/components/core/*"
  - "packages/config/*"
  - "packages/core/*"
  - "scripts"

hoistPatterns:
  - "react"
  - "react-dom"
